title: "EduConnect"
theme: minima

header_pages:
  - UserGuide.md
  - DeveloperGuide.md
  - AboutUs.md

markdown: kramdown

repository: "AY2526S1-CS2103-F11-1/tp"
github_icon: "images/github-icon.png"

remote_theme: pages-themes/architect@v0.2.0

plugins:
  - jemoji
  - jekyll-remote-theme # add this line to the plugins list if you already have one
